# Generated by Django 3.2.8 on 2021-11-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=300, null=True)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('profile_image_url', models.URLField(max_length=2000, null=True)),
                ('login_platform', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('pined_boards', models.ManyToManyField(blank=True, null=True, related_name='users', through='boards.PinBoard', to='boards.Board')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
