# Generated by Django 3.2.9 on 2021-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_platform_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
